# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_normativact_podchin',
            name='normact',
        ),
        migrations.RemoveField(
            model_name='t_normativact_podchin',
            name='signername',
        ),
        migrations.RemoveField(
            model_name='t_normativact_podchin2',
            name='normact',
        ),
        migrations.RemoveField(
            model_name='t_normativact_podchin2',
            name='signername',
        ),
        migrations.AlterModelOptions(
            name='t_acceptancers',
            options={'verbose_name': 'Утверждающие'},
        ),
        migrations.AlterModelOptions(
            name='t_docsubtype',
            options={'verbose_name': 'Вид документа'},
        ),
        migrations.AlterModelOptions(
            name='t_doctype',
            options={'verbose_name': 'Тип документа'},
        ),
        migrations.AlterModelOptions(
            name='t_executor',
            options={'verbose_name': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='t_mainexecutor',
            options={'verbose_name': 'Ответственный исполнитель'},
        ),
        migrations.AlterModelOptions(
            name='t_normativact',
            options={'verbose_name': 'Нормативные акты'},
        ),
        migrations.AlterModelOptions(
            name='t_publicationlocate',
            options={'verbose_name': 'Место опубликования'},
        ),
        migrations.AlterModelOptions(
            name='t_signers',
            options={'verbose_name': 'Подписывающие'},
        ),
        migrations.AlterModelOptions(
            name='t_signing',
            options={'verbose_name': 'Вид подписания'},
        ),
        migrations.AlterModelOptions(
            name='t_status',
            options={'verbose_name': 'Статус документа'},
        ),
        migrations.AlterModelOptions(
            name='t_theme',
            options={'verbose_name': 'Тема документа'},
        ),
        migrations.AddField(
            model_name='t_normativact',
            name='ageementers',
            field=models.ManyToManyField(to='Editor.T_Acceptancers'),
        ),
        migrations.AddField(
            model_name='t_normativact',
            name='signers',
            field=models.ManyToManyField(to='Editor.T_Signers'),
        ),
        migrations.AlterField(
            model_name='t_acceptancers',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='t_docsubtype',
            name='subtype',
            field=models.CharField(max_length=200, verbose_name='Вид документа'),
        ),
        migrations.AlterField(
            model_name='t_doctype',
            name='doctype',
            field=models.CharField(max_length=200, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='t_executor',
            name='executor',
            field=models.CharField(max_length=200, verbose_name='Исполнитель документа'),
        ),
        migrations.AlterField(
            model_name='t_mainexecutor',
            name='mainexecutor',
            field=models.CharField(max_length=200, verbose_name='Ответственный исполнитель'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='addonscount',
            field=models.IntegerField(verbose_name='колво приложений'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='archivedelo',
            field=models.CharField(max_length=200, verbose_name='Дело №'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='archivetom',
            field=models.CharField(max_length=200, verbose_name='Том №'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='controldate',
            field=models.DateField(verbose_name='дата контроля'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='controloff',
            field=models.BooleanField(verbose_name='снято с контроля'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='numofnewspaper',
            field=models.CharField(max_length=200, verbose_name='№ газеты'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='pagescount',
            field=models.IntegerField(verbose_name='кол-во листов'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='publicatedate',
            field=models.DateField(verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='publicateflag',
            field=models.BooleanField(verbose_name='подлежит опубликованию'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='regdate',
            field=models.DateField(verbose_name='Регистрационная дата'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='regnum',
            field=models.CharField(max_length=200, verbose_name='Рег. №'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='result',
            field=models.BooleanField(verbose_name='результат исполнения'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='sheetscount',
            field=models.IntegerField(verbose_name='Листы'),
        ),
        migrations.AlterField(
            model_name='t_normativact',
            name='topic',
            field=models.CharField(max_length=2000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='t_publicationlocate',
            name='publicatedin',
            field=models.CharField(max_length=200, verbose_name='Где опубликовано'),
        ),
        migrations.AlterField(
            model_name='t_signers',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='t_signing',
            name='typeossigning',
            field=models.CharField(max_length=200, verbose_name='Подписание документа'),
        ),
        migrations.AlterField(
            model_name='t_status',
            name='status',
            field=models.CharField(max_length=200, verbose_name='Статус документа'),
        ),
        migrations.AlterField(
            model_name='t_theme',
            name='theme',
            field=models.CharField(max_length=2000, verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='T_NormativAct_podchin',
        ),
        migrations.DeleteModel(
            name='T_NormativAct_podchin2',
        ),
    ]
